#!/bin/bash

work=media
more=vws

while (( ${#} )); do
    case ${1} in
        -w=*)
            work=${1##*=}
            shift
            ;;
        -m=*)
            more=${1##*=}
            shift
            ;;
        *)
            shift
            ;;
    esac
done


source ./misc
source ./more/${more}/main


root=./more/${more}/work

mkdir -p ${root}

for f in       \
    kernel.bin \
    custom.dtb \
    rootfs.img \
    qemu       \
    runq       \
    para       \
    snap       \
    emu        \
    debug.cfg  \
    trace      \
    trace.cfg  \
    timing     \
    timing.cfg; do
    ln -sf ${f} ${root}/${f}
done

cd ${root} && main
