#!/bin/bash

copy() {
    if [[ ${#} -ne 2 ]]; then
        return
    fi

    local dst=${1}
    local src=${2}

    mv ${src}/adv               ${dst}
    mv ${src}/trace.log         ${dst}
    mv ${src}/trace.bin         ${dst}
    mv ${src}/stats_db.out.gz   ${dst}/trace.gz
    mv ${src}/configuration.out ${dst}/timing.cfg

    mv ${dst}/stats_db.out.gz   ${dst}/timing.gz
    mv ${dst}/configuration.out ${dst}/timing.cfg
}

if [[ ${BASH_SOURCE[0]} == ${0} ]]; then
    copy ${@}
fi
