#!/bin/bash

set -e

file=para.cmd
core=45
args=()

while (( ${#} )); do
    case ${1} in
        -file=*)
            file=${1##*=}
            shift
            ;;
        -core=*)
            core=${1##*=};
            shift
            ;;
        *)
            args+=(${1})
            shift
            ;;
    esac
done

export FLEXUS_CFG_OVERRIDE="${args[*]}"

exec parallel --env FLEXUS_CFG_OVERRIDE --arg-file ${file} --max-lines 1 --max-procs ${core}
