#!/usr/bin/python3

import os
import sys

import argparse


def parse_args():
    args = argparse.ArgumentParser(description = 'run')

    args.add_argument('-t', default = '0')
    args.add_argument('-e', default = 'media')
    args.add_argument('-x', default = 'vws')

    return args.parse_known_args()[0]


def prep(work, exp):
    def link(src, dst):
        for f in os.listdir(src):
            if not os.path.islink(d := os.path.join(dst, f)):
                os.symlink(os.path.abspath(os.path.join(src, f)), d)

    exp = os.path.join('exp', exp)

    os.makedirs(work, exist_ok = True)

    link('bin', work)
    link('cfg', work)
    link('dat', work)
    link('lib', work)
    link( exp,  work)

    os.chdir(work)

    # enable importing from .
    sys.path.insert(0, '')


if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    args = parse_args()

    if os.uname().nodename.startswith('iccluster'):
        prep(os.path.join('/', 'mnt', 'sdb', os.environ['USER'], 'out'), args.x)
    else:
        prep(os.path.join('out'), args.x)

    import main
    main.main(args.t, args.e)
