#!/usr/bin/python3

import os

import argparse
import importlib


def parse_args():
    args = argparse.ArgumentParser(description='run')

    args.add_argument('-e', default='media')
    args.add_argument('-x', default='vws')

    return args.parse_args()


def prepare(work):
    def link(src, dst):
        for f in os.listdir(src):
            if not os.path.islink(d := os.path.join(dst, f)):
                os.symlink(os.path.abspath(os.path.join(src, f)), d)

    os.makedirs(work, exist_ok = True)

    link('bin', work)
    link('cfg', work)
    link('dat', work)
    link('lib', work)

    os.chdir(work)


if __name__ == '__main__':
    args = parse_args()

    prepare(os.path.join('exp', args.x, 'work'))

    xmod = importlib.import_module(f'exp.{args.x}.run')
    xmod.run(args.e)