#!/usr/bin/python

import os
import sys

import matplotlib.pyplot as pp


def parse(fn):
    real = []
    fake = []

    with open(fn + '-real.out') as fd:
        real = list(map(int, fd.readlines()))

    with open(fn + '-fake.out') as fd:
        fake = list(map(int, fd.readlines()))

    indx = list(range(len(real)))

    pp.plot(indx, real, label = 'real')
    pp.plot(indx, fake, label = 'fake')

    pp.legend()
    pp.show()


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(f'usage: {sys.argv[0]} <out>')

    parse(sys.argv[1])
