#!/bin/bash

set -e

if [[ ${#} -eq 0 ]]; then
    exit
fi

snap=${1} && shift

export FLEXUS_LOG_OVERRIDE=timing.log

exec ./runq ${RUNQ_ARGS} +timing +snap=${snap}/adv +stdout=${snap}/adv/timing.out +stderr=-
