#!/usr/bin/zsh

set -e

cd ${0:A:h:h}

exp=vws
dir=1-8k_32k_2m
bin=media
tds=0
mod=timing

while (( ${#} )); do
    case ${1} in
        -e=*)
            exp=${1##*=}
            ;;
        -d=*)
            dir=${1##*=}
            ;;
        -b=*)
            bin=${1##*=}
            ;;
        -t=*)
            tds=${1##*=}
            ;;
        -m=*)
            mod=${1##*=}
            ;;
    esac

    shift
done

mkdir -p tmp

aux/calc_lat "exp/${exp}/work/results/${dir}/${bin}_${tds}_\\d+_\\d+/${mod}.bin$"       \
    > tmp/${tds}.${dir}.lat.csv

aux/calc_pmc "exp/${exp}/work/results/${dir}/${bin}_${tds}_\\d+_\\d+/${mod}.gz$" ${mod} \
    > tmp/${tds}.${dir}.pmc.csv
