#!/usr/bin/python

import os
import sys

import libdraw as ld


def draw(fn, ext = ''):
    if not ext:
        sys.exit(f'ERROR: ext not specified')

    if not os.path.isfile(fn):
        sys.exit(f'ERROR: {fn} not found')

    with ld.Draw(fn + '.pdf') as (f, a):
        match ext:
            case 'q1':
                cs = ['Load', 'B-tree', 'Plain list', 'Ideal']
            case 'q2':
                cs = ['Load', '1', '8', '32', 'Ideal']
            case 'q2i':
                cs = ['Load', '1', '2', 'Ideal']

        d = ld.Data(cols = cs,
                    file = fn).unwrap()

        match ext:
            case 'q1' | 'q2' | 'q2i':
                for n in cs[1:]:
                    a.plot(d['Load'], d[n], label = n)

        match ext:
            case 'q1' | 'q2i':
                nc = 3
            case 'q2':
                nc = 6

        a.format(xlabel = 'Load (KRPS)',
                 ylabel = 'Throughput (KRPS)',
                 ymin   =  0,
                 ymax   =  500,
                 xmin   =  0,
                 xmax   =  500)

        a.legend(loc = 't', ncols = nc)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        draw(*sys.argv[1:])
