#!/usr/bin/python

import os
import sys

import libdraw as ld


def draw(fn, ext = ''):
    if not os.path.isfile(fn):
        sys.exit(f'ERROR: {fn} not found')

    with ld.Draw(fn + '.pdf') as (f, a):
        cs = ['Load', '1', '4', '8', '16', '32', '64']

        if ext:
            cs.append('PL')

        d = ld.Data(cols = cs,
                    file = fn).unwrap()

        a.plot(d['Load'], d['1' ], label = '1x')
        a.plot(d['Load'], d['4' ], label = '4x')
        a.plot(d['Load'], d['8' ], label = '8x')

        if ext:
            a.plot(d['Load'], d['PL'], label = '64x Plain List')

        a.plot(d['Load'], d['16'], label = '16x')
        a.plot(d['Load'], d['32'], label = '32x')
        a.plot(d['Load'], d['64'], label = '64x')

        a.format(xlabel = 'Load (KRPS)',
                 ylabel = '99th Percentile Latency (us)',
                 ymin   =  0,
                 ymax   =  1000,
                 xmin   =  0,
                 xmax   =  180)

        a.hlines(140, 0, 180, lw = 1, ls = 'dotted', color = 'red')
        a.hlines(700, 0, 180, lw = 1, ls = 'dotted', color = 'red')

        a.text(2, 160, '2x SLO')
        a.text(2, 720, '10x SLO')

        a.legend(loc = 't', ncols = 4 if ext else 3)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        draw(*sys.argv[1:])
