#!/usr/bin/python

import os
import sys

import libdraw as ld


def draw(fn, ext = ''):
    if not os.path.isfile(fn):
        sys.exit(f'ERROR: {fn} not found')

    with ld.Draw(fn + '.pdf') as (f, a):
        match ext:
            case 'q1':
                cs = ['Load', 'Plain list', 'B-tree']
            case '':
                cs = ['Load', '1', '4', '8', '16', '32', '64']
            case 'all':
                cs = ['Load', '1', '4', '8', '16', '32', '64', '64 Plain list']

        d = ld.Data(cols = cs,
                    file = fn).unwrap()

        match ext:
            case 'q1':
                for n in cs[1:]:
                    a.plot(d['Load'], d[n], label = n)
            case _:
                for n in cs[1:]:
                    a.plot(d['Load'], d[n], label = f'{n[:2]}x{n[2:]}')

        match ext:
            case 'q1':
                ym = 400
                nc = 2
            case '':
                ym = 180
                nc = 3
            case 'all':
                ym = 180
                nc = 4

        a.format(xlabel = 'Load (KRPS)',
                 ylabel = 'Throughput (KRPS)',
                 ymin   =  0,
                 ymax   =  ym,
                 xmin   =  0,
                 xmax   =  ym)

        a.legend(loc = 't', ncols = nc)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        draw(*sys.argv[1:])
