#!/usr/bin/python

import os
import sys

import libdraw as ld


def draw(fn, ext = ''):
    if not os.path.isfile(fn):
        sys.exit(f'ERROR: {fn} not found')

    with ld.Draw(fn + '.pdf') as (f, a):
        cs = ['Assoc', '32', '64', '128', '256', '512']

        d = ld.Data(cols = cs,
                    file = fn).unwrap()

        for n in cs[1:]:
            a.plot(d['Assoc'], d[n], linestyle = '-', label = n)

        a.format(xlabel = 'Associativity',
                 ylabel = 'Throughput Difference (KRPS)',
                 ymin   =  0,
                 ymax   =  10,
                 xmin   =  0,
                 xmax   =  9)

        a.legend(loc = 't', ncols = 5)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        draw(*sys.argv[1:])
