#!/usr/bin/python

import os
import sys

import libdraw as ld


def draw(fn):
    if not os.path.isfile(fn):
        sys.exit(f'ERROR: {fn} not found')

    with ld.Draw(fn + '.pdf') as (f, a):
        d = ld.Data(cols = ['Load', '1', '4', '8', '16', '32', '64'],
                    file = fn).unwrap()

        a.plot(d['Load'], d['1' ], label = '1x')
        a.plot(d['Load'], d['4' ], label = '4x')
        a.plot(d['Load'], d['8' ], label = '8x')
        a.plot(d['Load'], d['16'], label = '16x')
        a.plot(d['Load'], d['32'], label = '32x')
        a.plot(d['Load'], d['64'], label = '64x')

        a.format(xlabel = 'Load (KRPS)',
                 ylabel = 'Throughput (KRPS)',
                 ymin   =  0,
                 ymax   =  180,
                 xmin   =  0,
                 xmax   =  180)

        a.legend(loc = 't', ncols = 3)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        draw(sys.argv[1])
