#!/usr/bin/python3

import os
import sys

import matplotlib.pyplot as pp


def parse(fn):
    fn = os.path.splitext(fn)[0]

    fake = []
    real = []
    user = []
    iret = []

    with open(f'{fn}-0-fake.out') as fd:
        fake = list(map(int, fd.readlines()))

    with open(f'{fn}-0-real.out') as fd:
        real = list(map(int, fd.readlines()))

    with open(f'{fn}-0-user.out') as fd:
        user = list(map(int, fd.readlines()))

    with open(f'{fn}-0-iret.out') as fd:
        iret = list(map(int, fd.readlines()))

    x = list(range(len(real)))

    pp.plot(x, fake, label = 'fake')
    pp.plot(x, real, label = 'real')
    pp.plot(x, user, label = 'user')
    pp.plot(x, iret, label = 'iret')
    pp.ylim(0, 1e6)

    pp.legend()
    pp.show()


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(f'usage: {sys.argv[0]} <out>')

    parse(sys.argv[1])
